name: Make + clang tidy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
defaults:
  run:
    shell: bash
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v3
      with:
        repository: cheyao/Achieve-Core
    - name: Install tools
      run: |
        sudo apt-get -y install llvm
        sudo apt-get -y install lld
        git submodule update --init --recursive
    - name: make
      run: CC=clang LD=ld.lld make -C Achieve-BIOS
    - name: check syntax
      run: |
        echo "\`\`\`\n" >> $GITHUB_STEP_SUMMARY
        make -C Achieve-BIOS clang-tidy >> $GITHUB_STEP_SUMMARY
